### ISSUE TITLE
Finetuning on custom dataset

### ISSUE THREAD

**Issue by ajinkya2903** [yg211/bert_nli#6]
Hey I am finetuning bert base on custom nli dataset. But while starting a training process it is getting stuck at the error stating that **torch.nn.modules.module.ModuleAttributeError: 'BertEncoder' object has no attribute 'output_hidden_states'**. Can you solve this as as I want to get this done as soon as possible?

**Comment by yg211** [comment]
Hi there,

please use transformers 3.0.2; that should solve the problem.

**Comment by ajinkya2903** [comment]
Thanks for your quick reply. I tried installing transformers version 3.0.2 yet it is giving me the same error. I am attaching screenshot of error please can you tell me where I am going wrong? Thank You so much 
![image](https://user-images.githubusercontent.com/63385842/96371679-774db700-1180-11eb-95d9-7bdc2c8c87ed.png)

**Comment by ilos-vigil** [comment]
I experience same error when running `example.py`, but i managed to solve it by downgrade `transformers` to 2.8.0 (i choose this version based on `requirements.txt` on older commit)

For reference, i use Python 3.6 on Linux.

**Comment by ajinkya2903** [comment]
Thanks @ilos-vigil it worked.
