### ISSUE TITLE
After completion of training getting this error.

### ISSUE THREAD

**Issue by ajinkya2903** [yg211/bert_nli#7]
I have trained distilbert model on my custom data. It has completed the training but after completion, it is giving the error. When I checked the .py file I am not getting the cause. Can I get the solution for this?
![image](https://user-images.githubusercontent.com/63385842/99178531-fad7d500-2739-11eb-87d0-b263f6a44cf1.png)

**Comment by yg211** [comment]
Hi there,

The training does not take place in the first place. The first line of output complains that 'libcudart.so.10.1' cannot be found. The second line suggests that GPU was not correctly set up on your machine. 

I would suggest installing CUDA correctly and re-install pytorch according to your CUDA version.

**Comment by ajinkya2903** [comment]
Thanks for replying but my system doesn't have CUDA so how can I start
the training process? If possible can you suggest me the way as I need to
do this an urgent basis.

Thank You

**Comment by yg211** [comment]
You could enforce the code to use CPU instead of GPU to train:
python train.py --gpu 0

BTW: the code currently doesn't support distill-BERT. It supports bert-base, bert-large, and albert.
