### ISSUE TITLE
Error in loading state_dict for BertNLIModel

### ISSUE THREAD

**Issue by keshav2995** [yg211/bert_nli#8]
I was trying to run the example script, but it seems to give this error **_Missing key(s) in state_dict: "bert.embeddings.position_ids"._** 
I tried instantiating model =  BertNLIModel('output/bert-base.state_dict') but it gives the same error. 
Any idea why?

**Comment by yg211** [comment]
Hi there,

The problem is most likely caused by transformers versions. Please make sure you use 

torch==1.0.1.post2
transformers==2.8.0

and it should be working. Please let me know if it doesn't solve the problem.
